### ISSUE TITLE
请问一下大佬，这个如何实现重载啊

### ISSUE THREAD

**Issue by djhdj1** [zsummer/fn-log#31]
源代码 是这样的
`UsageEnvironment& operator<<(UsageEnvironment& env, const RTSPClient& rtspClient) {
	return env << "[URL:\"" << rtspClient.url() << "\"]: ";
}`
我想用大佬的日志进行输出`*rtspclient`应该怎么操作，感谢大佬

**Comment by djhdj1** [comment]
还有个问题就是使用 安卓NDK21.3进行编译时会报错`\include\fn_log.h:2072: error: use of undeclared identifier 'gcvt'
..\qtstreamdecode1\include\fn_log.h:2072:25: error: use of undeclared identifier 'gcvt'
            char* buf = gcvt(number, 16, dst);
                        ^`

**Comment by zsummer** [comment]
FNLog::LogStream& operator << (FNLog::LogStream& ls, RTSPClient& rtspClient)
{
    return ls << rtspClient.name();
}

**Comment by zsummer** [comment]
> 
ndk这个加个头文件试试 
#include <stdlib.h>
